version: "3.9"

services:
  backend:
    container_name: service
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: miniblog_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: miniblog
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
